MASC-3.0.0  2012-12-15
----------------------

Full documentation for the MASC data and processing tools is
available at http://www.anc.org/data/masc.

DATA DESCRIPTION
----------------
See http://www.anc.org/data/masc/corpus

CONTENTS
--------

data - 
   spoken - data and annotations for spoken data
   written - data and annotations for written data

   See http://www.anc.org/data/masc/masc-structure for 
   details on the organization of MASC data and annotation files
 
   original-annotations - Contains annotations contributed to MASC in 
        their original format, as prepared by an external annotation 
        project. Versions of these annotations that have been transduced 
        to GrAF XML are included in the data directories. In general, 
        errors in the originals are left uncorrected.

MASC-resource-header.xml - 
   Comprehensive information about the corpus, contents, 
   organization, domain codes, naming conventions, etc. 

README-MASC3.0.0.txt - 
   This document

 
RELEASE 3.0.0 NOTES
-------------------

Quid Pro Quo
------------

Although every effort has been made to validate MASC annotations, there 
are likely still errors, omissions, and inconsistencies. Because MASC is a 
collaborative community resource, we ask the community to report errors so 
that we can correct them. We will release immediate updates through 
the MASC website at http://www.anc.org/data/masc/downloads/data-download/. 
Periodic updates will also be made available through LDC.

Known Problems
--------------

Penn POS tags

The current Penn POS tags, generated by a modified version of GATE's ANNIE 
Part-of-speech tagger, have not been fully validated. All Penn treebank (ptbtok)
and FrameNet (fntok) POS tags are hand-validated. The remainder of MASC is 
currently being annotated for Penn Treebank syntax, at which point the entire corpus 
will have hand-annotated POS tags.


Penn Treebank Tokens

There remain a few problems with the Penn Treebank tokenizations, 
primarily due to corrections to the texts made by the Treebank project
in the course of generating the original annotations. In some cases,
we have corrected the tokenizations to refer to the faulty text 
segment (e.g., "o" for "off" due to removal of ligatures in the 
course of transduction from original Quark Express files) and added 
an annotation named "corrected" whose value provides the correction to 
the text.


Event co-reference

The original GATE annotations done at Carnegie-Mellon University used the 
annotation set name internal to GATE to group events that co-refer. This information 
is lost once the annotations are output in any other format. The event co-reference 
annotations included in MASC are therefore a subset of those in the originals, and do 
not include the grouping information contained in the annotation set names. The 
differences can be seen by loading both the MASC event annotations and the original 
CMU annotations into GATE. 

Tweets

A few non-English tweets appear in the Twitter files.

CONTACT
-------

MASC is a product of the American National Corpus project. 

Email: anc@anc.org

Department of Computer Science
Vassar College
Poughkeepsie, New York 12604-0520 
USA


